version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular-service: # name of the first service
    image: lala14/eduflex-frontend
    container_name: angular-container
    
    build: ./ # specify the directory of the Dockerfile
    volumes: # Volume binding
    - './:/usr/src/app'
    ports:
      - "4200:4200" # specify port forewarding
    # command: 
    #   CMD ["npm", "start"]

  springboot-docker-container:
    image: lala14/eduflex-backend
    container_name: eduflex-backend
    ports:
      - 2020:2020
    build:
      context: /home/lala/Documents/Jenkins/Practice/eduflex-backend-master/
      dockerfile: Dockerfile



#   docker-nginx:
#     container_name: docker-nginx
#     build: ./
#     ports: 
#         - "80:80"
#     command: ["nginx", "-g", "daemon off;"]    
#     links: 
#         - angular-service

